# def analyze_sales(orders):
#     ...

# Given:

# orders = [
#     {
#         "order_id": 101,
#         "customer": "Rahul",
#         "items": [
#             {"product": "Laptop", "category": "Electronics", "price": 60000, "quantity": 1},
#             {"product": "Mouse", "category": "Electronics", "price": 1000, "quantity": 2}
#         ]
#     },
#     {
#         "order_id": 102,
#         "customer": "Priya",
#         "items": [
#             {"product": "Phone", "category": "Electronics", "price": 30000, "quantity": 1},
#             {"product": "Headphones", "category": "Electronics", "price": 2000, "quantity": 2}
#         ]
#     },
#     {
#         "order_id": 103,
#         "customer": "Amit",
#         "items": [
#             {"product": "Shoes", "category": "Fashion", "price": 3000, "quantity": 2},
#             {"product": "T-Shirt", "category": "Fashion", "price": 1200, "quantity": 3}
#         ]
#     }
# ]
# Your function should calculate:

# 1. Total revenue

# For every item:

# price × quantity

# Calculate the total revenue from all orders.

orders = [
    {
        "order_id": 101,
        "customer": "Rahul",
        "items": [
            {"product": "Laptop", "category": "Electronics", "price": 60000, "quantity": 1},
            {"product": "Mouse", "category": "Electronics", "price": 1000, "quantity": 2}
        ]
    },
    {
        "order_id": 102,
        "customer": "Priya",
        "items": [
            {"product": "Phone", "category": "Electronics", "price": 30000, "quantity": 1},
            {"product": "Headphones", "category": "Electronics", "price": 2000, "quantity": 2}
        ]
    },
    {
        "order_id": 103,
        "customer": "Amit",
        "items": [
            {"product": "Shoes", "category": "Fashion", "price": 3000, "quantity": 2},
            {"product": "T-Shirt", "category": "Fashion", "price": 1200, "quantity": 3}
        ]
    }
]

def analyze_sales(orders):
    total_revenue = 0

    for order in orders:
        

        for items in order["items"]:
            total_revenue += items["price"] * items["quantity"]

# 2. Revenue by category  

    rev_by_cat = {}

    for order in orders:

        for items in order["items"]:
            category = items["category"]
            revenue = items["price"] * items["quantity"]

            if category not in rev_by_cat:
                rev_by_cat[category] = 0

            rev_by_cat[category] += revenue


               
# Revenue generated by each customer

    customer_revenue = {}

    for order in orders:
        customer = order["customer"]
        revenue = sum(item["price"] * item["quantity"] for item in order["items"])
        customer_revenue[customer] = revenue

# Find the highest-spending customer
    
    highest_spend = orders[0]["items"][0]["price"]   

    for order in orders:
        customer = order["customer"]
        rev = sum(item["price"] * item["quantity"] for item in order["items"])
        if rev > highest_spend:
            highest_spend = rev
            highest_customer = customer


# Find products generating more than ₹5,000 revenue

    high_revenue_products = []

    for order in orders:
        for item in order["items"]:
            rev = item["price"] * item["quantity"]

            if rev > 5000:
                high_revenue_products.append({
                    "product": item["product"],
                    "revenue": rev
                })
                    

    result = {
        "total_revenue": total_revenue,
        "revenue_by_category": rev_by_cat,
        "customer_revenue": customer_revenue,
        "highest_customer": highest_customer,
        "high_revenue_products": high_revenue_products
    }

    return result




result = analyze_sales(orders)
print(result)   